#!/bin/bash

firefox --url http://homeassistant.local:8123/ --url https://www.messenger.com/ --url https://www.cnbc.com/markets/ --url https://secure03b.chase.com/web/auth/dashboard#/dashboard/overviewAccounts/overview/index --url https://www.usaa.com/inet/ent_logon/Logon 
