#!/usr/bin/env perl

$lsblk = qx/lsblk --exclude 7 --output MOUNTPOINT,NAME --pairs --paths/;
@problems = $lsblk =~ m{(MOUNTPOINT=(?!(""|"\[SWAP\]"|"/"|"/boot.*")).+)}g;

if (@problems){
    @msg = "";
    push(@msg, "It may not be safe to shutdown while the following devices");
    push(@msg, "are mounted!\n\n");
    foreach (@problems){ 
        if ($_){
            $name = $1 if $_ =~ m/NAME="(.+)"/;
            push(@msg, "$name\n");
        }
    }

    qx/notify-send -t 10000 'Unexpected mounted devices!' "@msg\n"/;
    qx/dmenu-prompt critical "External devices still connected. Shutdown anyway?" \
        'shutdown now'/;
}else{
    qx/shutdown now/;
}


