#!/bin/bash

set -e

autoloaddir="$HOME/.vim/autoload"
bundledir="$HOME/.vim/bundle"

mkdir -p "$autoloaddir" "$bundledir"
curl -LSo "$autoloaddir/pathogen.vim" "https://tpo.pe/pathogen.vim"

get-update-specific-package(){
    dir="$1"
    giturl="$2"

    echo "Working on $1 ..."

    if [ ! -d "$dir" ] ; then
        git clone --depth 1 "$giturl" "$dir"
    else
        pushd "$dir"
        git pull origin master
        popd
    fi

    echo "Done with $1"
}

pushd $bundledir

get-update-specific-package "ctrlp" "https://github.com/ctrlpvim/ctrlp.vim"
get-update-specific-package "commentary" "https://github.com/tpope/vim-commentary"
get-update-specific-package "nerdtree" "https://github.com/scrooloose/nerdtree"
get-update-specific-package "syntastic" "https://github.com/vim-syntastic/syntastic"
get-update-specific-package "repeat" "https://github.com/tpope/vim-repeat"
get-update-specific-package "vim-airline" "https://github.com/vim-airline/vim-airline"
get-update-specific-package "vim-surround" "https://github.com/tpope/vim-surround"

popd
