#!/bin/bash

# This function expects these params
# 1: The url to download
# 2: The final name of the file
# 3: The directory to put the final file
download() {
	youtube-dl --verbose --restrict-filename --extract-audio --ffmpeg-location /snap/bin/ --audio-format mp3 "$1" --exec "mv {} $3/$2.mp3"
}

restingPlace="$1"
inputFile="$2"

if [ -z "$restingPlace" ] ; then
    echo "First argument needs to be the location to save the file to."
    exit 1
fi
if [ -z "$inputFile" ] ; then
    echo "Second argument needs to be path to input file."
    exit 1
fi

pushd ~/Music

if [ ! -f "$inputFile" ] ; then
    echo "Cannot find file $inputFile"
    exit 1
fi

if [ ! -d "$restingPlace" ]; then
	echo "Creating $restingPlace"
	
	# I'm not sure if the -p option helps things?
	mkdir -p "$restingPlace"
fi

while IFS=, read -r url name; do
    download "$url" "$name" "$restingPlace"
done < "$2";

popd
