
name: plexmediaserver
vars:
  tar_dir: /var/local/docker/plex
  tar_exclude:
    - "Library/Application Support/Plex Media Server/Cache/*"
    - "Library/Application Support/Plex Media Server/Logs/*"